version: "3.9"

services:
  db:
    image: postgres:16
    container_name: gitea-db
    restart: always
    environment:
      POSTGRES_USER: gitea
      POSTGRES_PASSWORD: gitea_pass
      POSTGRES_DB: gitea
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - gitea-net

  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    restart: always
    depends_on:
      - db
    environment:
      GITEA__database__DB_TYPE: postgres
      GITEA__database__HOST: db:5432
      GITEA__database__NAME: gitea
      GITEA__database__USER: gitea
      GITEA__database__PASSWD: gitea_pass

      GITEA__server__DOMAIN: localhost
      GITEA__server__ROOT_URL: http://localhost:3000/
      GITEA__server__HTTP_PORT: 3000
    volumes:
      - gitea_data:/data
    ports:
      - "3000:3000"
    networks:
      - gitea-net

volumes:
  db_data:
  gitea_data:

networks:
  gitea-net:
    driver: bridge
